<?php

use \PHPUnit\Framework\TestCase;
require "BerlinClock.php";

class BerlinClockTest extends TestCase
{
    private $berlinClock;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->berlinClock = new BerlinClock();
    }

    public function testSample() {
        //Arrange

        //Act

        //Assert
        $this->assertTrue(true);
    }

    public function test_translate_given1_shouldReturn1Yellow() {
        $actual = $this->berlinClock->translate(1);

        $this->assertEquals(["yellow"], $actual);
    }

    public function test_translate_given2_shoudReturn2Yellow() {
        $actual = $this->berlinClock->translate(2);

        $this->assertEquals(["yellow", "yellow"], $actual);
    }
}
