<?php

use \PHPUnit\Framework\TestCase;
require "BerlinClock.php";

class BerlinClockTest extends TestCase
{
    private $berlinClock;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->berlinClock = new BerlinClock();
    }

    public function testSample() {
        //Arrange

        //Act

        //Assert
        $this->assertTrue(true);
    }

    public function test_translate_given1_shouldReturn1Yellow() {
        $actual = $this->actTranslate(1);

        $this->assertEquals(["yellow"], $actual);
    }

    public function test_translate_given2_shouldReturn2Yellow() {
        $actual = $this->actTranslate(2);

        $this->assertEquals(["yellow", "yellow"], $actual);
    }

    public function test_translate_given3_shouldReturn3Yellow() {
        $actual = $this->actTranslate(3);

        $this->assertEquals(["yellow", "yellow", "yellow"], $actual);
    }

    public function test_translate5Minutes_given5_shouldReturn1Yellow() {
        $actual = $this->actTranslate5Minutes(5);

        $this->assertEquals(["yellow"], $actual);
    }

    public function actTranslate(int $int)
    {
        return $this->berlinClock->translate($int);
    }

    public function actTranslate5Minutes(int $int)
    {
        return $this->berlinClock->translate5Minutes($int);
    }
}
